# Generated by Django 4.2.13 on 2024-06-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DormApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_type', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=200, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.student')),
            ],
        ),
    ]
