# Generated by Django 4.2.13 on 2024-06-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_student_status_alter_visitor_reason_dormapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormapply',
            name='reason',
        ),
        migrations.AddField(
            model_name='dormapply',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
