# Generated by Django 4.2.13 on 2024-06-16 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_dormapply_reason_dormapply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormapply',
            name='applicant_date',
            field=models.DateField(default=datetime.date(2024, 6, 16)),
        ),
    ]
