# Generated by Django 4.2.13 on 2024-06-17 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_dormapply_applicant_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperUser',
        ),
        migrations.AlterField(
            model_name='dorm',
            name='Dorm_id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dormapply',
            name='applicant_date',
            field=models.DateField(default=datetime.date(2024, 6, 17)),
        ),
    ]
