# Generated by Django 4.2.13 on 2024-06-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_delete_superuser_alter_dorm_dorm_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dorm',
            new_name='dorm_id',
        ),
    ]
