# Generated by Django 4.2.13 on 2024-06-17 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_rename_dorm_id_student_dorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgupload',
            name='title',
            field=models.CharField(default='<built-in method now of type object at 0x00007FFDCE334650>', max_length=100),
        ),
        migrations.AddField(
            model_name='imgupload',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.student'),
        ),
    ]
