# Generated by Django 4.2.13 on 2024-06-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_imgupload_title_imgupload_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.imgupload'),
        ),
    ]
