# Generated by Django 4.2.13 on 2024-06-18 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_student_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dorm',
            new_name='dorm_id',
        ),
        migrations.AlterField(
            model_name='dormapply',
            name='applicant_date',
            field=models.DateField(default=datetime.date(2024, 6, 18)),
        ),
        migrations.AlterField(
            model_name='imgupload',
            name='title',
            field=models.CharField(default='<built-in method now of type object at 0x00007FFDA1294650>', max_length=100),
        ),
    ]
