# Generated by Django 4.2.13 on 2024-06-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_dorm_student_dorm_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dorm_id',
            new_name='dorm',
        ),
    ]
